FROM gcc:13

# Install standalone Asio headers on Debian-based image
RUN apt-get update && apt-get install -y --no-install-recommends \
    libasio-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy your C++ project folder into the container
COPY mini_redis/ ./mini_redis

# Compile the server (Asio headers now exist in /usr/include)
RUN g++ -std=c++20 mini_redis/src/server.cpp -o server -pthread

EXPOSE 6379

CMD ["./server"]

