foreground = yes
pid = /tmp/stunnel.pid
client = yes

[vector-tls]
accept = 0.0.0.0:16379
connect = vector-tls-server:16379
cert = /etc/stunnel/certs/client.crt
key = /etc/stunnel/certs/client.key
CAfile = /etc/stunnel/certs/ca.crt
verify = 2
