foreground = yes
pid = /tmp/stunnel.pid

[vector-tls]
accept = 0.0.0.0:16379
connect = redis:6379
cert = /etc/stunnel/certs/server.crt
key = /etc/stunnel/certs/server.key
CAfile = /etc/stunnel/certs/ca.crt
verify = 2
